#!/usr/bin/env ruby
#
# Copyright (c) 2014 William C. Benton and Red Hat, Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.


USE_ERUBIS = false

if USE_ERUBIS

  require 'erubis'

  class Instantiator
    DEFAULT_OPTIONS = {:safe_level => 3}

    def initialize(hash, options = nil)
      @vars = hash.dup
      @options = DEFAULT_OPTIONS.merge((options || {}))
    end

    def process(input)
      Erubis::Eruby.new(template).result(@vars)
    end
  end

else # USE_ERUBIS

  require 'erb'

  class Instantiator
    DEFAULT_OPTIONS = {:safe_level => 3}
    
    # this is the least terrible way to instantiate ERb with a hash
    # source: http://stackoverflow.com/a/5462069/192616
    class Namespace
      def initialize(hash)
        hash.each do |key, value|
          puts "adding a binding for #{key} => #{value}" if $LEITMOTIF_DEBUG
          singleton_class.send(:define_method, key) { value }
        end 
      end

      def get_binding
        binding
      end
    end
    
    def initialize(vars, options = nil)
      @options = DEFAULT_OPTIONS.merge((options || {}))
      @ns = Namespace.new(vars)
    end
  
    def process(template)
      vars = @ns.get_binding
      
      vars.untaint
      template.untaint
      
      # XXX: $SAFE level should be irrelevant here; only the supplied bindings should be available
      ERB.new(template, @options[:safe_level]).result(vars)
    end
  end

end # USE_ERUBIS


require 'fileutils'
require 'find'
require 'open3'
require 'yaml'


module LMProcessHelpers
  
  def spawn_and_capture(*cmd)
    Open3.popen3(*cmd) do |stdin, stdout, stderr, wait_thr|
      exit_status = wait_thr.value
      raise "command '#{cmd.inspect}' failed; more details follow:  #{stderr.read}" unless exit_status == 0
      stdout.read
    end
  end
  
  def spawn_with_input(str, *cmd)
    out, err, s = Open3.capture3(*cmd, :stdin_data=>str)
    raise "command '#{cmd.inspect}' failed; more details follow:  #{err}" unless s.exitstatus == 0
    [out, err]
  end
end

module LMPath
  def self.localPrototypeStore
    File.join(Dir.home, ".leitmotif-prototypes")
  end
  
  def check_output_dir(outputDir)
    if File.exists?(outputDir)
      if @options[:clobber]
        FileUtils.rm_rf(outputDir)
      else
        raise "#{outputDir} already exists; move it first"
      end
    end
  end
  
  def ensure_exists(path)
    unless File.exists?(path)
      FileUtils.mkdir_p(path)
    end
    path
  end
end

class PrototypeCreator
  DEFAULT_OPTIONS = {:git => "/usr/bin/git", 
      :verbose => false, 
      :debug => false, 
      :clobber => false,
      :local => false,
      :edit => false,
      :author => nil,
      :email => nil,
      :commit_message => "Initial revision"}
  
  include LMProcessHelpers
  include LMPath
  
  def initialize(name, options = nil)
    @options = DEFAULT_OPTIONS.merge(options || {})
    @options[:author] ||= spawn_and_capture(%W{#{@options[:git]} config --global user.name}).strip
    @options[:email] ||= spawn_and_capture(%W{#{@options[:git]} config --global user.email}).strip
    @name = name
    
    ensure_exists(LMPath::localPrototypeStore) if @options[:local]
  end
  
  def create()
    outputDir = @options[:local] ? File.join(LMPath::localPrototypeStore, @name) : @name
    check_output_dir(outputDir)
    ensure_exists(outputDir)
    
    oldcwd = Dir.getwd()
    Dir.chdir(outputDir)
    
    begin
      spawn_and_capture(%W{#{@options[:git]} init})
      o,e = spawn_with_input(make_history_file, %W{#{@options[:git]} fast-import})
      puts o if @options[:debug]
      puts e if @options[:debug]
      spawn_and_capture(%W{#{@options[:git]} checkout -b master refs/head/master})
      
      exec([ENV["EDITOR"],ENV["EDITOR"]], File.realpath(outputDir)) if @options[:edit]
    ensure
      Dir.chdir(oldcwd)
    end
    
    0
  end
  
  private
  
  def make_history_file()
    metadata = "---\n:name: #{@name}\n:version: '0'\n:required: []\n:ignore: []\n:defaults: {}\n"
    readme = "This is an empty Leitmotif prototype.  For details on how to set it up,\nplease see https://github.com/willb/leitmotif/wiki\n"
    ts = Time.now.strftime('%s %z')
    <<-eos
blob
mark :1
data #{metadata.length}
blob
mark :2
data #{readme.length}
reset refs/head/master
commit refs/head/master
mark :3
author #{@options[:author]} <#{@options[:email]}> #{ts}
committer #{@options[:author]} <#{@options[:email]}> #{ts}
data #{@options[:commit_message].length}
M 100644 :1 .leitmotif
M 100644 :2 proto/README
done

eos
  end
    
end

class LocalPrototypeStore
  DEFAULT_OPTIONS = {:git => "/usr/bin/git", 
      :verbose => false, 
      :clobber => false}
  
  def initialize(options = nil)
    @options = DEFAULT_OPTIONS.merge(options || {})
    @localps = LMPath::localPrototypeStore
    ensure_exists(@localps)
  end
  
  include LMProcessHelpers
  include LMPath
  
  def cloneProto(remoteURL)
    begin
      prototypeName = prototype_name(remoteURL)
      spawn_and_capture(%W{#{@options[:git]} clone #{remoteURL} "#{File.join(LMPath::localPrototypeStore, prototypeName)}"})
      0
    rescue Exception=>ex
      puts "error:  #{ex}"
      puts ex.backtrace.join("\n") if (@options[:verbose] || $LEITMOTIF_DEBUG)
      1
    end
  end
  
  def list()
    begin
      Dir[File.join(LMPath::localPrototypeStore, "*")].each do |proto|
        puts prototype_name(proto)
      end
      0
    rescue Exception=>ex
      puts "error:  #{ex}"
      puts ex.backtrace.join("\n") if (@options[:verbose] || $LEITMOTIF_DEBUG)
      1
    end
  end
  
  private
  def prototype_name(url)
    url.split("/").pop.gsub(".git", "")
  end
  
end

class Leitmotif
  DEFAULT_OPTIONS = {:git => "/usr/bin/git", 
      :tar => "/usr/bin/tar", 
      :default_treeish => "master", 
      :verbose => false, 
      :clobber => false,
      :local => false}
  
  def initialize(hash = nil, options = nil)
    @bindings = (hash || {}).dup
    @options = DEFAULT_OPTIONS.merge(options || {})
  end
  
  def run(prototype, outputDir)
    begin
      if @options[:local]
        prototype = File.join(LMPath::localPrototypeStore, prototype)
      end
      
      _run(prototype, outputDir)
    rescue Exception=>ex
      puts "error:  #{ex}"
      puts ex.backtrace.join("\n") if (@options[:verbose] || $LEITMOTIF_DEBUG)
      1
    end
  end
  
  private
  def _run(prototype, outputDir)
    check_output_dir(outputDir)
    
    meta, archive = get_meta_and_proto(prototype, (@options[:ref] || @options[:default_treeish]))
    ymeta = YAML.load(meta)
    
    raise "#{prototype} doesn't look like a leitmotif prototype" unless (ymeta && list_proto(archive).size > 0)
    
    hash = (ymeta[:defaults] || {}).merge(@bindings).inject({}){|acc,(k,v)| acc[k.to_s] = v; acc}
    missing_required = (ymeta[:required] || []).select {|k| !hash.has_key?(k)}
    
    raise "prototype #{prototype} requires values for the following variables:  #{missing_required.join(", ")}" unless missing_required == []
    
    ignore = (ymeta[:ignore] || [])
    
    FileUtils.mkdir_p(outputDir)
    oldcwd = Dir.getwd()
    Dir.chdir(outputDir)
    
    begin
      unpack_proto!(archive)
      instantiator = Instantiator.new(hash)
      
      Find.find(".") do |templateFile|
        if File.ftype(templateFile) == "file" && !ignore.member?(templateFile)
          oldFile = File.open(templateFile, "r") {|f| f.read}
          result = instantiator.process(oldFile)
          File.open(templateFile, "w") {|f| f.write(result)}
        end
      end
    ensure
      Dir.chdir(oldcwd)
    end
    0
  end
  
  def get_meta_and_proto(remote, treeish = nil)
    meta = nil
    proto = nil
    
    begin
      treeish ||= @options[:default_treeish]
      meta = get_meta(remote, treeish)
      proto = get_proto(remote, treeish)
    rescue Exception=>ex
      raise "can't load leitmotif prototype and metadata: #{ex}"
    end
    
    [meta, proto]
  end
  
  def get_meta(remote, treeish = nil)
    treeish ||= @options[:default_treeish]
    metaArchive = spawn_and_capture(%W{#{@options[:git]} archive --remote #{remote} #{treeish} .leitmotif})
    meta, = spawn_with_input(metaArchive, %W{#{@options[:tar]} xO .leitmotif})
    meta
  end
  
  def get_proto(remote, treeish = nil)
    treeish ||= @options[:default_treeish]
    spawn_and_capture(%W{#{@options[:git]} archive --remote #{remote} #{treeish} proto})
  end
  
  def unpack_proto!(archive)
    spawn_with_input(archive, %W{#{@options[:tar]} x --strip 1})
  end
  
  def list_proto(archive)
    out, err = spawn_with_input(archive, %W{#{@options[:tar]} t})
    out.split("\n")
  end

  include LMProcessHelpers
end

require "rubygems"
require "thor"

module CLIHelpers
  def symbolize_hash(hash)
    hash.inject({}){|acc,(k,v)| acc[k.to_sym] = v; acc}
  end
end
  

class LeitmotifCLI < Thor
  desc "generate PROTOTYPE OUTPUT_DIR", "instantiate PROTOTYPE into OUTPUT_DIR"
  method_option :clobber, :type => :boolean, :desc => "overwrite OUTPUT_DIR if it exists"
  method_option :verbose, :type => :boolean, :desc => "provide additional debugging output"
  method_option :local, :type => :boolean, :desc => "use a prototype from the user's local prototype store"
  method_option :debug, :type => :boolean, :desc => "provide way too much additional debugging output"
  method_option :ref, :type => :string, :desc => "git tree-ish to use for PROTOTYPE instantiation"
  method_option :bindings, :type => :hash, :desc => "variable bindings for PROTOTYPE instantiation, in the form KEY:VALUE"
  def generate(prototype, output_dir)
    $LEITMOTIF_DEBUG = options["debug"]
    
    puts "prototype is #{prototype}" if $LEITMOTIF_DEBUG
    puts "output_dir is #{output_dir}" if $LEITMOTIF_DEBUG
    puts "options are #{options.inspect}" if @LEITMOTIF_DEBUG
    symbolized_options = symbolize_hash(options)
    exit(Leitmotif.new(symbolized_options[:bindings], symbolized_options).run(prototype, output_dir))
  end
  
  desc "clone URL", "clone a remote prototype from URL to the local prototype store"
  method_option :verbose, :type => :boolean, :desc => "provide additional debugging output"
  method_option :debug, :type => :boolean, :desc => "provide way too much additional debugging output"
  def clone(url)
    exit(LocalPrototypeStore.new(symbolize_hash(options)).cloneProto(url))
  end
  
  desc "list", "show locally-installed prototypes"
  method_option :verbose, :type => :boolean, :desc => "provide additional debugging output"
  method_option :debug, :type => :boolean, :desc => "provide way too much additional debugging output"
  def list()
    exit(LocalPrototypeStore.new(symbolize_hash(options)).list())
  end
  
  desc "new-prototype NAME", "create a new leitmotif prototype named NAME"
  method_option :local, :type => :boolean, :desc => "create the new prototype in the local store"
  method_option :clobber, :type => :boolean, :desc => "overwrite destination if it exists"
  method_option :edit, :type => :boolean, :desc => "open the new prototype immediately with $EDITOR"
  method_option :verbose, :type => :boolean, :desc => "provide additional debugging output"
  method_option :debug, :type => :boolean, :desc => "provide way too much additional debugging output"
  def new_prototype(name)
    exit(PrototypeCreator.new(name, symbolize_hash(options)).create())
  end

  private
  include CLIHelpers
end

LeitmotifCLI.start

